* The Astrochelys Pelican Theme
This is the theme we use for [[https://out-of-cheese-error.netlify.app/][OutOfCheeseError]]
** Basic Usage 
1. Start a blog using [[https://docs.getpelican.com/en/stable/quickstart.html][Pelican]]
2. Clone this repository alongside your ~pelicanconf.py~
3. Add THEME = "./astrochelys" to ~pelicanconf.py~
4. Add [[https://github.com/ingwinlu/pelican-toc][pelican-toc]] to your PLUGINS. This can be customized as described [[https://github.com/ingwinlu/pelican-toc#settings][here]].

** Customizations
*** Analytics
Astrochelys supports both [[https://analytics.google.com/analytics/web/][Google]] and [[https://usefathom.com/][Fathom]] analytics. 
- To use Google Analytics, set the ~GOOGLE_ANALYTICS~ variable in ~pelicanconf.py~ to your Analytics ID.
- To use Fathom, set the ~FATHOM_SITE_ID~ variable to the site ID given by Fathom, and the ~FATHOM_ANALYTICS~ variable to the server address performing the tracking (We use [[https://github.com/usefathom/fathom][Fathom Lite]] hosted on [[https://www.heroku.com/][Heroku]] for this, following the instructions [[https://github.com/usefathom/fathom/blob/master/docs/misc/Heroku.md#create-the-app][here]].)

*** Comments
Astrochelys provides comments using either [[https://hypothes.is/][Hypothesis]] or [[https://disqus.com/][Disqus]] (or both). Disqus support is controlled by the variable ~DISQUS_SITENAME~ in ~pelicanconf.py~. Hypothesis is embedded in the header and appears on the right side of the page.

*** Search
Astrochelys supports search via [[https://github.com/tinysearch/tinysearch][tinysearch]] and some JS code taken from [[https://github.com/mre/mre.github.io][Matthias Endler's blog source]]. To set this up:
+ Install tinysearch and terser as described in the tinysearch repository 
+ Add a ~json.md~ file in ~your_pelican_directory/content/pages~ with
#+BEGIN_SRC md
Title: JSON
Template: json
Slug: json
#+END_SRC
+ Set the ~ADD_SEARCH_BOX~ variable to ~True~ in ~pelicanconf.py~ 
+ Finally, add the following to your pelican ~Makefile~:
#+BEGIN_SRC makefile
  .PHONY: index
  index: content ## Build the search index with tinysearch
          tinysearch --optimize --path $(OUTPUTDIR) $(OUTPUTDIR)/pages/json.html
  .PHONY: minify
  minify: ## Compress JavaScript assets
          terser --compress --mangle --output $(OUTPUTDIR)/search_min.js -- $(OUTPUTDIR)/tinysearch_engine.js

  .PHONY: build
  build: html index minify ## Build static site and search index, minify JS
#+END_SRC
and instead of running ~pelican content~ to build your output files run ~make build~ instead.

*** Colors & Fonts
- All website colors and fonts are defined in the first few lines of ~static/css/astrochelys.css~, change these for a different theme. 
- Syntax highlighting colors are defined in ~static/css/pygments.css~. Change this to any pygments theme you like.

*** Margin notes
See [[https://out-of-cheese-error.netlify.app/astrochelys#org6d6ec31][here]] on how to add margin notes to your articles.

** More
Every line of code in excruciating detail over at [[https://out-of-cheese-error.netlify.app/astrochelys][this post]]. 

